apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    enterprise: staging

# namespace: devtroncd
resources:
- ../../base/

patches:
- patch: |-
    - op: replace
      path: /spec/templates/0/dag/tasks/0/arguments/parameters/0/value
      value: "devtron-orchestrator"
    - op: replace
      path: /spec/templates/0/dag/tasks/1/arguments/parameters/0/value
      value: "devtron-orchestrator"
    - op: replace
      path: /spec/arguments/parameters/3/value
      value: "staging"
    - op: replace
      path: /spec/arguments/parameters/4/value
      value: "staging-dcd"
  target:
    group: argoproj.io
    version: v1alpha1
    kind: Workflow
    name: release


namePrefix: stage-
nameSuffix: -wf
