apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    enterprise: otpless

# namespace: devtroncd
resources:
- ../../base/

patches:
- patch: |-
    - op: replace
      path: /spec/arguments/parameters/3/value
      value: "otpless"
    - op: replace
      path: /spec/arguments/parameters/4/value
      value: "otpless-dcd"
  target:
    group: argoproj.io
    version: v1alpha1
    kind: Workflow
    name: release


namePrefix: otpless-
nameSuffix: -wf
