name: Enterprise Task
description: "Tasks related to an Enterprise"
title: "ENTT: "
assignees: ["prakarsh-dt","pawan-59"]
projects: ["devtron-labs/6"]
labels: ["ENTERPRISE"]
body:
  - type: dropdown
    id: enterprise-name
    attributes:
      label: enterprise-name
      description: Which Enterprise is this task related to
      options:
        - Others (ENT)
        - Others (OSS)
        - 1MG
        - 73Strings
        - Ather
        - Bharatpe
        - BirdEye
        - BlueCopa
        - Cyble
        - Delhivery
        - Delhivery-Platform
        - Empuls
        - OTPLess
        - TheKhelGroup
        - Lemnisk
        - Spinny
        - Chitale
        - Indiamart
  - type: dropdown
    id: task-type
    attributes:
      label: Task type
      description: Which type of task is this
      options:
        - Devtron Product
        - Cleanup
        - Developers queries
        - QA queries
        - Security
        - Compliances
        - Installer
        - Releases
        - Automation
        - SRE
        - Infra
  - type: input
    id: zoho-ticket
    attributes:
      label: Zoho Ticket ID (If exists)
      description: ZohoDesk ticket ID
      placeholder: #11
    validations:
      required: false
  - type: textarea
    id: task-description
    validations:
      required: true
    attributes:
      label: "Task description"
      description: "A clear and concise description of what the task is."
      placeholder: "You should add ..."
  - type: textarea
    id: tasklist
    validations:
      required: false
    attributes:
      label: "Subtasks List (If any)"
      description: "A clear list of sub-tasks if any. The list items may contain the link to other github issues or just the text."
      placeholder: "- [ ]  https://github.com/devtron-labs/devtron/issues/4482 (Sub-task link, the sub task is automatically marked completed when the issue is closed )"
