name: SRE Tasks
description: "Tasks related to SRE activities"
title: "SRE: "
assignees: ["prakarsh-dt","tayalrishabh96"]
projects: ["devtron-labs/6"]
labels: ["SRE"]
body:
  - type: dropdown
    id: task-type
    attributes:
      label: Task type
      description: Which type of task is this
      options:
        - Devtron Services
        - External tools
        - Monitoring/Dashboards
        - Alerting
        - Others
  - type: textarea
    id: task-description
    validations:
      required: true
    attributes:
      label: "Task description"
      description: "A clear and concise description of what the task is."
      placeholder: "You should add ..."
  - type: textarea
    id: tasklist
    validations:
      required: false
    attributes:
      label: "Subtask (If any)"
      description: "A clear list of sub-tasks if any. The list items may contain the link to other github issues or just the text."
      placeholder: "- [ ]  https://github.com/devtron-labs/devtron/issues/4482 (Sub-task link, the sub task is automatically marked completed when the issue is closed )"
