---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: release
  namespace: argo
  annotations:
    workflows.argoproj.io/description: |
      This is a sample workflow for enterprise releases using DAG
spec:
  ttlStrategy:
    secondsAfterCompletion: 3600
  serviceAccountName: argo
  entrypoint: release
  onExit: notify
  archiveLogs: true
  artifactRepositoryRef:
    configMap: azure-blob-wf-logs-cm
    key: artifactRepository
  arguments:
    parameters:
    - name: DEVTRON_BASE_URL
      value: cd.devtron.ai
    - name: USE_HTTPS
      value: "true"
    - name: LOG_LEVEL
      value: "-1"
    - name: ENTERPRISE_NAME
      value: devtron
    - name: ENV_NAME
      value: cd-devtroncd
    - name: ENV_ID
      value: None

  templates:
  - name: release
    dag:
      tasks:
      - name: update-orchestrator-cm
        template: bulk-edit
        arguments:
          parameters:
          - name: APP_NAMES
            value: orchestrator
          - name: CM_NAMES
            value: orchestrator-cm
          - name: CM_DATA
            value: '{"replace":{"APP_SYNC_IMAGE":"quay.io/devtron/chart-sync:d0dcc590-132-21155","DEFAULT_CI_IMAGE":"quay.io/devtron/ci-runner:dd5dffd2-515-21154","USE_GIT_CLI": "true"}}' 
      - name: orchestrator-release
        dependencies: ["update-orchestrator-cm", "kubelink-release"]
        template: trigger-deploy
        arguments:
          parameters:
          - name: APP_NAME
            value: orchestrator
          - name: SOURCE_COMMIT_HASH
            value: 6946a78d2cfda4c215027067d36b29ecdc744b63
      - name: update-kubewatch-cm
        template: bulk-edit
        arguments:
          parameters:
          - name: APP_NAMES
            value: kubewatch
          - name: CM_NAMES
            value: kubewatch-cm
          - name: CM_DATA
            value: '{"replace":{"DEMO_KEY":"DEMO_VALUE"}}'
      - name: kubewatch-release
        dependencies: ["update-kubewatch-cm"]
        template: trigger-deploy
        arguments:
          parameters:
          - name: APP_NAME
            value: kubewatch
          - name: SOURCE_COMMIT_HASH
            value: 91c2cecef6cbbb3023320ba1753d6a8f0eea60d4
      - name: update-git-sensor-cm
        template: bulk-edit
        arguments:
          parameters:
          - name: APP_NAMES
            value: git-sensor
          - name: CM_NAMES
            value: git-sensor-cm
          - name: CM_DATA
            value: '{"replace":{"DEMO_KEY":"DEMO_VALUE"}}'
      - name: git-sensor-release
        dependencies: ["update-git-sensor-cm"]
        template: trigger-deploy
        arguments:
          parameters:
          - name: APP_NAME
            value: git-sensor
          - name: SOURCE_COMMIT_HASH
            value: 03493b42a3d3c6ffeb74d8e6b314682beb180125
      - name: update-lens-cm
        template: bulk-edit
        arguments:
          parameters:
          - name: APP_NAMES
            value: lens
          - name: CM_NAMES
            value: lens-cm
          - name: CM_DATA
            value: '{"replace":{"DEMO_KEY":"DEMO_VALUE"}}'
      - name: lens-release
        dependencies: ["update-lens-cm"]
        template: trigger-deploy
        arguments:
          parameters:
          - name: APP_NAME
            value: lens
          - name: SOURCE_COMMIT_HASH
            value: 70577aaa1ad185d4e145999bccf072144647eddc
      - name: update-image-scanner-cm
        template: bulk-edit
        arguments:
          parameters:
          - name: APP_NAMES
            value: image-scanner-new
          - name: CM_NAMES
            value: image-scanner-cm
          - name: CM_DATA
            value: '{"replace":{"DEMO_KEY":"DEMO_VALUE"}}'
      - name: image-scanner-release
        dependencies: ["update-image-scanner-cm"]
        template: trigger-deploy
        arguments:
          parameters:
          - name: APP_NAME
            value: image-scanner-new
          - name: SOURCE_COMMIT_HASH
            value: 1e0b2312a0fa49c4189b194ada75706cae576457
      - name: update-kubelink-cm
        template: bulk-edit
        arguments:
          parameters:
          - name: APP_NAMES
            value: kubelink
          - name: CM_NAMES
            value: kubelink-cm
          - name: CM_DATA
            value: '{"replace":{"DEMO_KEY":"DEMO_VALUE"}}'
      - name: kubelink-release
        dependencies: ["update-kubelink-cm"]
        template: trigger-deploy
        arguments:
          parameters:
          - name: APP_NAME
            value: kubelink
          - name: SOURCE_COMMIT_HASH
            value: 8bf60a10ef76c306f56c4a1d3b00c21224a9fe24
      - name: update-casbin-cm
        template: bulk-edit
        arguments:
          parameters:
          - name: APP_NAMES
            value: casbin
          - name: CM_NAMES
            value: casbin-cm
          - name: CM_DATA
            value: '{"replace":{"DEMO_KEY":"DEMO_VALUE"}}'
      - name: casbin-release
        dependencies: ["update-casbin-cm"]
        template: trigger-deploy
        arguments:
          parameters:
          - name: APP_NAME
            value: casbin
          - name: SOURCE_COMMIT_HASH
            value: 8f0b4a58e45abbe513b7288f6735958556458641
      - name: update-dashboard-cm
        template: bulk-edit
        arguments:
          parameters:
          - name: APP_NAMES
            value: dashboard
          - name: CM_NAMES
            value: dashboard-cm
          - name: CM_DATA
            value: '{"replace":{"ENABLE_EXTERNAL_ARGO_CD":"false"}}'
      - name: dashboard-release
        dependencies: ["update-dashboard-cm", "orchestrator-release"]
        template: trigger-deploy
        arguments:
          parameters:
          - name: APP_NAME
            value: dashboard
          - name: SOURCE_COMMIT_HASH
            value: 4ee7597eb5de5e23abdac61ad0476ecc7fdc74ce
  - name: notify
    steps:
    - - name: notify-success
        template: notifier
        when: "{{workflow.status}} == Succeeded"
        arguments:
          parameters:
          - name: EMBED_COLOR
            value: 65280

      - name: notify-failure
        template: notifier
        when: "{{workflow.status}} != Succeeded"
        arguments:
          parameters:
          - name: EMBED_COLOR
            value: 16711680

  - name: bulk-edit
    inputs:
      parameters:
      - name: APP_NAMES
      - name: IS_GLOBAL
        default: "false"
      - name: CM_NAMES
        default: "None"
      - name: CM_DATA
        default: "null"
      - name: SECRET_NAMES
        default: "None"
      - name: SECRET_DATA
        default: "null"
    container:
      image: quay.io/devtron/devtron-utils:workflow-dag-v2.1
      command: [sh, -c]
      args: ["python3 bulk-edit.py"]
      env:
      - name: DEVTRON_BASE_URL
        value: "{{workflow.parameters.DEVTRON_BASE_URL}}"
      - name: DEVTRON_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: release-dag-secret
            key: token
      - name: USE_HTTPS
        value: "{{workflow.parameters.USE_HTTPS}}"
      - name: LOG_LEVEL
        value: "{{workflow.parameters.LOG_LEVEL}}"
      - name: APP_NAMES
        value: "{{inputs.parameters.APP_NAMES}}"
      - name: ENV_NAMES
        value: "{{workflow.parameters.ENV_NAME}}"
      - name: ENV_IDS
        value: "{{workflow.parameters.ENV_ID}}"
      - name: IS_GLOBAL
        value: "{{inputs.parameters.IS_GLOBAL}}"
      - name: CM_NAMES
        value: "{{inputs.parameters.CM_NAMES}}"
      - name: CM_DATA
        value: "{{inputs.parameters.CM_DATA}}"
      - name: SECRET_NAMES
        value: "{{inputs.parameters.SECRET_NAMES}}"
      - name: SECRET_DATA
        value: "{{inputs.parameters.SECRET_DATA}}"
  - name: trigger-deploy
    inputs:
      parameters:
      - name: APP_NAME
      - name: SOURCE_COMMIT_HASH
      - name: TIMEOUT_SECONDS
        default: "600"
    container:
      image: quay.io/devtron/devtron-utils:workflow-dag-v2.1
      command: [sh, -c]
      args: ["python3 trigger-deploy.py"]
      env:
      - name: DEVTRON_BASE_URL
        value: "{{workflow.parameters.DEVTRON_BASE_URL}}"
      - name: DEVTRON_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: release-dag-secret
            key: token
      - name: LOG_LEVEL
        value: "{{workflow.parameters.LOG_LEVEL}}"
      - name: USE_HTTPS
        value: "{{workflow.parameters.USE_HTTPS}}"
      - name: APP_NAME
        value: "{{inputs.parameters.APP_NAME}}"
      - name: ENV_NAME
        value: "{{workflow.parameters.ENV_NAME}}"
      - name: SOURCE_COMMIT_HASH
        value: "{{inputs.parameters.SOURCE_COMMIT_HASH}}"
      - name: TIMEOUT_SECONDS
        value: "{{inputs.parameters.TIMEOUT_SECONDS}}"

  - name: notifier
    inputs:
      parameters:
      - name: EMBED_COLOR
      - name: AVATAR_URL
        default: "https://artifacthub.io/image/98440df4-0317-4777-8a92-3d7aead03382@3x"
    script:
      image: curlimages/curl:8.1.2
      command: [sh]
      source: |
        curl -H 'Content-Type: application/json' -d '{"username": "DAG-Hook", "avatar_url": "{{inputs.parameters.AVATAR_URL}}", "embeds": [{"title": "[{{workflow.status}}] Workflow Status {{workflow.status}} for Enterprise {{workflow.parameters.ENTERPRISE_NAME}}", "color":{{inputs.parameters.EMBED_COLOR}}}]}' $DISCORD_WEBHOOK_URL
      env:
      - name: DISCORD_WEBHOOK_URL
        valueFrom:
          secretKeyRef:
            name: release-dag-secret
            key: discord_url
